name: Swift Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14  # Zorgt ervoor dat we een recente macOS-versie gebruiken met nieuwere Xcode-versies.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Select Xcode met Swift 6
      run: sudo xcode-select -s /Applications/Xcode_15.3.app || sudo xcode-select -s /Applications/Xcode_15.2.app

    - name: Verifieer Swift-versie
      run: swift --version

    - name: Build project
      run: swift build -v

    - name: Run tests
      run: swift test -v
