name: Swift Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15  # Gebruik macOS 15 voor compatibiliteit met Swift 6.0.

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Verifieer Swift-versie
      run: swift --version

    - name: Build project
      run: swift build -v

    - name: Run tests
      run: swift test -v
